# This config is used for the CI workflow.
# Feel free to also use it locally for fast builds if you have the required setup!

[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

# Compile deps with LLVM because cranelift can crash the test runner otherwise
[profile.dev.package."*"]
codegen-backend = "llvm"

# Disable cranelift for release profile
[profile.release]
codegen-backend = "llvm"

# cranelift cannot build wasm32-unknown-unknown out of the box
[profile.web]
codegen-backend = "llvm"

# Override the high opt-level from the dev profile for the test profile
[profile.test.package."*"]
opt-level = 1

[target.wasm32-unknown-unknown]
# Clang does not support wasm32-unknown-unknown,
# so we cannot use mold either: https://github.com/flathub/org.freedesktop.Sdk.Extension.rust-stable/issues/168
linker = "lld"
rustflags = [
    "-Dwarnings",
    "-Cdebuginfo=line-tables-only",
    "--cfg",
    "getrandom_backend=\"wasm_js\"",
    # Nightly
    "-Zshare-generics=y",
    "-Zthreads=0",
]
rustdocflags = [
    "-Dwarnings",
    # Nightly
    "-Zshare-generics=y",
    "-Zthreads=0",
]


[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-Dwarnings",
    "-Cdebuginfo=line-tables-only",
    # Mold linker
    "-Clink-arg=-fuse-ld=mold",
    # Nightly
    "-Zshare-generics=y",
    "-Zthreads=0",
]
rustdocflags = [
    "-Dwarnings",
    # Mold linker
    "-Clink-arg=-fuse-ld=mold",
    # Nightly
    "-Zshare-generics=y",
    "-Zthreads=0",
]
