name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Run tests.
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustc-codegen-cranelift-preview

      - name: Install mold
        uses: rui314/setup-mold@v1

      - name: Active CI cargo config
        run: mv .cargo/config_ci.toml .cargo/config.toml

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Install dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev

      - name: Set LD_LIBRARY_PATH
        run: |
          # Setting LD_LIBRARY_PATH is a workaround for <https://github.com/TheBevyFlock/bevy_new_2d/pull/318#issuecomment-2585935350>.
          echo "LD_LIBRARY_PATH=$(rustc --print target-libdir)" >>"${GITHUB_ENV}"

      - name: Restore Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
          cache-directories: ${{ env.LD_LIBRARY_PATH }}

      - name: Run tests
        run: cargo nextest run --locked --workspace --all-features --all-targets --no-fail-fast --no-tests warn

      # Running doc tests separately is a workaround for <https://github.com/rust-lang/cargo/issues/6669>.
      - name: Run doc tests
        run: cargo test --locked --workspace --all-features --doc

  # Check that the game builds for web.
  check-web:
    name: Check web build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-unknown

      - name: Active CI cargo config
        run: mv .cargo/config_ci.toml .cargo/config.toml

      - name: Install dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev lld

      - name: Restore Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Check web build
        run: cargo check --config 'profile.web.inherits="dev"' --features dev --no-default-features --profile web --target wasm32-unknown-unknown


  # Run clippy lints.
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustc-codegen-cranelift-preview

      - name: Install mold
        uses: rui314/setup-mold@v1

      - name: Active CI cargo config
        run: mv .cargo/config_ci.toml .cargo/config.toml

      - name: Install dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev

      - name: Restore Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
          shared-key: lints

      - name: Run clippy lints
        run: cargo clippy --locked --workspace --all-targets --all-features

  # Check formatting.
  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  # Check documentation.
  doc:
    name: Docs
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustc-codegen-cranelift-preview

      - name: Install mold
        uses: rui314/setup-mold@v1

      - name: Active CI cargo config
        run: mv .cargo/config_ci.toml .cargo/config.toml

      - name: Install dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev

      - name: Restore Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
          shared-key: lints

      - name: Check documentation
        run: cargo doc --locked --workspace --all-features --document-private-items --no-deps

  # Run Bevy lints.
  bevy-lint:
    name: Bevy linter
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev

      - name: Restore Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install Bevy linter
        uses: TheBevyFlock/bevy_cli/bevy_lint@lint-v0.3.0

      - name: Add cranelift to rustc
        run: rustup component add rustc-codegen-cranelift-preview

      - name: Install mold
        uses: rui314/setup-mold@v1

      - name: Active CI cargo config
        run: mv .cargo/config_ci.toml .cargo/config.toml

      - name: Run Bevy linter
        run: bevy_lint --locked --workspace --all-targets --all-features
